apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cp-kafka-connect
    chart: cp-kafka-connect-0.1.0
    heritage: Tiller
    release: confluent
  name: confluent-cp-kafka-connect
  namespace: kafka
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cp-kafka-connect
      release: confluent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "5556"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: cp-kafka-connect
        release: confluent
    spec:
      containers:
      - command:
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -XX:MaxRAMFraction=1
        - -XshowSettings:vm
        - -jar
        - jmx_prometheus_httpserver.jar
        - "5556"
        - /etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
        image: solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
        imagePullPolicy: IfNotPresent
        name: prometheus-jmx-exporter
        ports:
        - containerPort: 5556
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/jmx-kafka-connect
          name: jmx-config
      - command:
        - sh
        - -exc
        - |
          export CONNECT_BOOTSTRAP_SERVERS=${CONFLUENT_CP_KAFKA_SERVICE_HOST}:9092 && \
          exec /etc/confluent/docker/run
        env:
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: PLAINTEXT://confluent-cp-kafka-headless:9092
        - name: CONNECT_GROUP_ID
          value: confluent
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: confluent-cp-kafka-connect-config
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: confluent-cp-kafka-connect-offset
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: confluent-cp-kafka-connect-status
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://confluent-cp-schema-registry:8081
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://confluent-cp-schema-registry:8081
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_PLUGIN_PATH
          value: /usr/share/java
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "3"
        - name: CONNECT_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: KAFKA_JMX_PORT
          value: "5555"
        image: confluentinc/cp-kafka-connect:5.2.2
        imagePullPolicy: IfNotPresent
        name: cp-kafka-connect-server
        ports:
        - containerPort: 8083
          name: kafka-connect
          protocol: TCP
        - containerPort: 5555
          name: jmx
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: confluent-cp-kafka-connect-jmx-configmap
        name: jmx-config
