apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: kafka
spec:
  containers:
  - command:
    - sh
    - -c
    - exec tail -f /dev/null
    image: solsson/kafka:0.11.0.0
    imagePullPolicy: IfNotPresent
    name: kafka
