#### Namespace and RBAC ####
apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logfilter-controller
  namespace: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: logfilter-controller
subjects:
  - kind: ServiceAccount
    name: logfilter-controller
    namespace: fluent-bit
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
#### Log Inputs ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-k8s-pod-logs
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/log: "true"
data:
  log_kind: k8s_pod_log
  path: /var/log/containers/*.log
  tag: kube.*
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-rke-container-logs
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/log: "true"
data:
  log_kind: rke_container_log
  path: /var/lib/rancher/rke/log/*.log
  tag: rke.*
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-syslog
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/log: "true"
data:
  log_kind: syslog
  path: /var/log/syslog
  tag: syslog.syslog
---
#### Process Monitorings ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-worker-procs
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/proc: "true"
data:
  proc_names: kubelet,dockerd
  interval_sec: "60"
  node_group: worker
  tag: proc.*
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-master-procs
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/proc: "true"
data:
  proc_names: kubelet,dockerd,kube-apiserver,kube-controller,kube-scheduler,etcd
  interval_sec: "60"
  node_group: master
  tag: proc.*
---
#### OS Monitorings ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-os
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/os: "true"
data:
  cpu_tag: os.cpu
  cpu_interval_sec: "60"
  memory_tag: os.memory
  memory_interval_sec: "60"
  io_tag: os.io
  io_interval_sec: "60"
  io_diskname: sda
  filesystem_tag: os.filesystem
  filesystem_interval_sec: "300"
  filesystem_df_dir: "/"
---
#### Pod/Node Metrics ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-pod-metrics
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/metric: "true"
data:
  metric_kind: pod
  interval_sec: "60"
  tag: metrics.pod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-node-metrics
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/metric: "true"
data:
  metric_kind: node
  interval_sec: "60"
  tag: metrics.node
---
#### k8s Apps Status ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: input-app-statuses
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/app: "true"
data:
  app_kinds: deployments,daemonsets,statefulsets
  interval_sec: "60"
  tag: apps.*
---
#### Outputs ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: output-es
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/es: "true"
data:
  match: "*"
  host: elasticsearch.fluent-bit.svc
  port: "9200"
  index_prefix: cluster01
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: output-kafka
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/kafka: "true"
data:
  match: "*"
  brokers: 10.10.10.1:9093,10.10.10.2:9093,10.10.10.3:9093
  timestamp_format: iso8601
  topics: cluster01
  rdkafka_options: ssl.key.location=/fluent-bit/kafka/certs/private-key.pem,ssl.certificate.location=/fluent-bit/kafka/certs/cert-signed.pem,ssl.ca.location=/fluent-bit/kafka/certs/ca-cert.pem,ssl.key.password=kafka1234,security.protocol=ssl
---
#### Node Groups ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/nodegroup: "true"
data:
  tolerations: ""
  node_selector: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: master
  namespace: fluent-bit
  labels:
    logfilter.ssl.com/nodegroup: "true"
data:
  tolerations: controlplane,etcd
  node_selector: controlplane
