apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit-logfilter
  namespace: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentbit-logfilter
  template:
    metadata:
      labels:
        app: fluentbit-logfilter
    spec:
      containers:
        - name: fluentbit-logfilter
          image: [image]:[tag]
          command:
            - /logfilter-controller
            - --fluentbitimage=fluent/fluent-bit:0.14
            - --metricsimage=[fluentbit-curl-jq]:[tag]
            - --namespace=fluent-bit
      serviceAccountName: logfilter-controller
