################################################
## fj3817ia/fluent-bit-curl-jq:0.3
## ... Copying back fluent-bit:1.2 into debian
## ... Adding jq, curl and procps
################################################

FROM fluent/fluent-bit:1.2 as builder

FROM gcr.io/google-containers/debian-base-amd64:0.3.1

RUN apt-get update \
  && apt-get dist-upgrade -y \
  && apt-get install --no-install-recommends ca-certificates libssl1.0.2 -y \
  && apt-get -y install curl jq procps \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get autoclean \
  && mkdir /host \
  && cp -r /bin /lib /lib64 /usr /host/

COPY --from=builder /fluent-bit /fluent-bit

EXPOSE 2020

# Entry point
CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
