apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fluent-bit
  name: fluentbit-config
  namespace: kube-system
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    error
        Parsers_File parsers.conf
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        DB               /var/log/containers/fluent-bit.kube.db
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/lib/rancher/rke/log/*.log
        DB               /var/lib/rancher/rke/log/fluent-bit.rke.db
        Parser           docker
        Tag              rke.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/log/syslog
        DB               /var/log/fluent-bit.syslog.db
        Path_Key         log_name
        Tag              syslog.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
    [INPUT]
        Name             tail
        Path             /var/log/docker.log
        DB               /var/log/fluent-bit.docker.db
        Path_Key         log_name
        Tag              docker.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    [FILTER]
        Name record_modifier
        Match *
        Record hostname ${HOSTNAME}
    [FILTER]
        Name lua
        Match rke.*
        script /fluent-bit/etc/funcs.lua
        call add_record
    [FILTER]
        Name lua
        Match *
        script /fluent-bit/etc/funcs.lua
        call ignore_message
    [OUTPUT]
        Name  es
        Match *
        Host  efk-elasticsearch
        Port  9200
        Logstash_Format On
        Retry_Limit False
        Type  flb_type
        Logstash_Prefix kubernetes_cluster
  parsers.conf: ""
