{
 "title": "k8s Pod Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 }, "content": "### System Error Logs" },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "!_exists_:kubernetes AND !_exists_:container_name AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error/Warn/Fail in System Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "!_exists_:kubernetes AND !_exists_:container_name AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error/Warn/Fail in System Logs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "!_exists_:kubernetes AND !_exists_:container_name AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "content": "### System Container Error Logs"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:container_name AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Err/Warn/Fail in System Containers Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 8 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_exists_:container_name  AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Err/Warn/Fail in System Containers Log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:container_name  AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 }, "content": "### Container Error Logs" },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:kubernetes AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Err/Warn/Fail in Containers Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_exists_:kubernetes  AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Err/Warn/Fail in Containers Log",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "_exists_:kubernetes  AND (log:\"error\" OR log:\"warning\" OR log:\"failed\" OR log:\"warn\" OR log:\"fail\") AND !_exists_:ignore_alerts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ignored Logs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "ignore_alerts.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:ignore_alerts",
       "timeField": "@timestamp"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 34 }, "content": "### System Logs" },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 34 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "!_exists_:kubernetes AND !_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Logs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "log_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "!_exists_:kubernetes AND !_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 34 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "!_exists_:kubernetes AND !_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Logs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "!_exists_:kubernetes AND !_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 42 }, "content": "### System Container Logs" },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 42 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Container Logs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "container_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Containers Log",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 42 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "System Containers Log",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:container_name",
       "timeField": "@timestamp"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 50 }, "content": "### Container Logs" },
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 50 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:kubernetes",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Container Logs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "kubernetes.container_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:kubernetes",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "k8s Pods Log",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 50 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "_exists_:kubernetes",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "k8s Pods Log",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "_exists_:kubernetes",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}