#### Lua scripts for metrics ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-metrics-lua
  namespace: fluent-bit
data:
  fluent-bit-metrics.lua: |-
    function cpu_memory_in_number(tag, timestamp, record)
      new_record = record
      cpu_num = string.gsub(record["cpu"],"m","")
      new_record["cpu_num"] = tonumber(cpu_num)
      memory_num = string.gsub(record["memory"],"Ki","")
      new_record["memory_num"] = tonumber(memory_num)
      return 1, timestamp, new_record
    end

    function exec2number(tag, timestamp, record)
      new_record = record
      new_record["num_exec"] = tonumber(record["exec"])
      return 1, timestamp, new_record
    end
---
#### Shells for node os monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: os-chk-scripts
  namespace: fluent-bit
data:
  chk_cpu.sh: |-
    #!/bin/sh

    HOST_DIR=$1

    user=0
    nice=0
    syst=0
    idle=0
    iowa=0
    per_val=1000

    stats=$(head -1 $HOST_DIR/proc/stat)

    if [ -e "/tmp/stats" ]; then
      total=0
      for val in $stats ; do
        if [ "$val" = "cpu" ] ; then
          continue
        fi
        total=$(($total + $val))
      done
      prev_total=0
      prev_stats=$(cat /tmp/stats)
      for val in $prev_stats ;  do
        if [ "$val" = "cpu" ] ; then
          continue
        fi
        prev_total=$(($prev_total + $val))
      done

      total=$(($total - $prev_total))

      user=$((($(echo $stats | awk '{print $2}') - $(echo $prev_stats | awk '{print $2}')) * $per_val / $total))
      nice=$((($(echo $stats | awk '{print $3}') - $(echo $prev_stats | awk '{print $3}')) * $per_val / $total))
      syst=$((($(echo $stats | awk '{print $4}') - $(echo $prev_stats | awk '{print $4}')) * $per_val / $total))
      idle=$((($(echo $stats | awk '{print $5}') - $(echo $prev_stats | awk '{print $5}')) * $per_val / $total))
      iowa=$((($(echo $stats | awk '{print $6}') - $(echo $prev_stats | awk '{print $6}')) * $per_val / $total))
    fi

    echo $stats > /tmp/stats

    # Output json
    echo {\"user\":$user,\"nice\":$nice,\"system\":$syst,\"idle\":$idle,\"iowait\":$iowa}

    return 0
  chk_filesystem.sh: |-
    #!/bin/sh

    DF_DIR=$1

    # disk size and usage
    df=$(df $DF_DIR | tail -1)
    name=$(echo $df | awk '{print $1}')
    size=$(echo $df | awk '{print $2}')
    used=$(echo $df | awk '{print $3}')
    free=$(echo $df | awk '{print $4}')

    # Output json
    echo {\"filesystem\":\"${name}\",\"size\":${size},\"used\":${used},\"free\":${free}}

    return 0
  chk_io.sh: |-
    #!/bin/sh

    DISK_NAME=$1
    HOST_DIR=$2

    # disk IOs
    read=0
    write=0
    sector=512
    prev_file="/tmp/diskstats-$DISK_NAME"

    stats=$(grep " $DISK_NAME " $HOST_DIR/proc/diskstats)

    if [ -e $prev_file ]; then
      elapsed=$(($(date +%s) - $(date +%s -r $prev_file)))
      prev_stats=$(cat $prev_file)
      read=$((($(echo $stats | awk '{print $6}') - $(echo $prev_stats | awk '{print $6}')) * $sector / $elapsed))
      write=$((($(echo $stats | awk '{print $10}') - $(echo $prev_stats | awk '{print $10}')) * $sector / $elapsed))
    fi

    echo $stats > $prev_file

    # Output json
    echo {\"disk_name\":\"${DISK_NAME}\",\"ioread\":${read},\"iowrite\":${write}}

    return 0
  chk_mem.sh: |-
    #!/bin/sh

    HOST_DIR=$1

    items="MemTotal MemFree MemAvailable Buffers Cached"

    for item in $items ; do
      val=$(grep -e ^$item: $HOST_DIR/proc/meminfo | awk '{print $2}')
      json="$json\"$item\":$val,"
    done

    # Output json
    echo "{${json%,}}"

    return 0
  chk_proc.sh: |-
    #!/bin/sh

    PROC_NAME=$1
    HOST_DIR=$2

    rss_total=0
    hwm_total=0
    cpu_total=0
    alive="false"
    pid=0
    proc_num=0
    pid_list=""

    # get ps c -C proc_name
    procs=$(chroot $HOST_DIR ps c -C $PROC_NAME --no-headers | awk '{printf "%d|%s\n",$1,$5}')

    for ps in $procs ; do
      # pid
      pid=$(echo $ps | cut -d'|' -f1)
      # memory
      hwm=$(grep VmHWM $HOST_DIR/proc/$pid/status | awk '{print $2}')
      rss=$(grep VmRSS $HOST_DIR/proc/$pid/status | awk '{print $2}')
      if [ "$hwm" != "" ]; then
        hwm_total=$(($hwm_total + $hwm))
      fi
      if [ "$rss" != "" ]; then
        rss_total=$(($rss_total + $rss))
      fi
      # cpu
      cgroup_path=$(grep cpuacct $HOST_DIR/proc/$pid/cgroup | cut -d':' -f3)
      if [ "$cgroup_path" != "/" ]; then
        cgroup_path=$HOST_DIR/sys/fs/cgroup/cpu,cpuacct${cgroup_path}/cpuacct.usage
        cpu_usage_nano=$(cat $cgroup_path)
        if [ -e "/tmp/$PROC_NAME-$pid-cpu" ]; then
          cpu_usage_nano_prev=$(cat /tmp/$PROC_NAME-$pid-cpu)
          elapsed=$(($(date +%s) - $(date +%s -r /tmp/$PROC_NAME-$pid-cpu)))
          cpu_usage=$((($cpu_usage_nano - $cpu_usage_nano_prev) / 1000000 / $elapsed))
        else
          cpu_usage=0
        fi
        echo $cpu_usage_nano > /tmp/$PROC_NAME-$pid-cpu
        cpu_total=$(($cpu_total + $cpu_usage))
      fi
      # proc_num
      proc_num=$(($proc_num + 1))
      # alive
      alive="true"
    done

    # Output json
    echo {\"alive\":$alive,\"pid\":$pid,\"cpu_msec\":$cpu_total,\"VmHWM\":$hwm_total,\"VmRSS\":$rss_total,\"proc_num\":$proc_num}

    return 0
