#### Lua scripts for metrics ####
apiVersion: v1
kind: ConfigMap
metadata:
  name: lua-filter-scripts
  namespace: fluent-bit
data:
  scripts.lua: |-
    function cpu_memory_in_number(tag, timestamp, record)
      new_record = record
      cpu_num = string.gsub(record["cpu"],"n","")
      new_record["cpu_num"] = tonumber(cpu_num) / 1000000
      memory_num = string.gsub(record["memory"],"Ki","")
      new_record["memory_num"] = tonumber(memory_num)
      return 1, timestamp, new_record
    end

    function exec2number(tag, timestamp, record)
      new_record = record
      new_record["num_exec"] = tonumber(record["exec"])
      return 1, timestamp, new_record
    end

    function add_flb_key(tag, timestamp, record)
      new_record = record
      new_record["_flb-key"] = tag
      return 1, timestamp, new_record
    end

    function add_record(tag, timestamp, record)
      new_record = record
      new_record["container_name"] = string.match( tag, "rke.var.lib.rancher.rke.log.(.*)_%w*.log" )
      return 1, timestamp, new_record
    end
